import ReactQueryProvider from "@/app/_providers/ReactQueryProvider";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import Navbar from "./_components/Navbar";
import { ToastContainer } from "react-toastify";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        dir="rtl"
        className={`relative sm:-8 p-4 bg-[#13131a] min-h-screen`}
      >
        <ReactQueryProvider>
          <Navbar />
          {children}
          <ToastContainer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
